// Default's actions
export const BASIC_INFO_FETCHED = "BASIC_INFO_FETCHED";
export const BASIC_INFO_ERROR = "BASIC_INFO_ERROR";

export const POOL_INFO_FETCHED = "POOL_INFO_FETCHED";
export const POOL_INFO_ERROR = "POOL_INFO_ERROR";

export const MINING_DATA_FETCHED = "MINING_DATA_FETCHED";
export const MINING_DATA_ERROR = "MINING_DATA_ERROR";
export const SUBMITTED_MAX_SUBMISSION = "SUBMITTED_MAX_SUBMISSION";

export const FOUND_BOOKMARKED_MINER = "FOUND_BOOKMARKED_MINER";
export const NOT_FOUND_BOOKMARKED_MINER = "NOT_FOUND_BOOKMARKED_MINER";

export const SIGNA_PRICE_FETCHED = "SIGNA_PRICE_FETCHED";
export const SIGNA_PRICE_ERROR = "SIGNA_PRICE_ERROR";

export const OPEN_MINER_MODAL = "OPEN_MINER_MODAL";
export const CLOSE_MINER_MODAL = "CLOSE_MINER_MODAL";

export const BLOCK_DATA_FETCHED = "BLOCK_DATA_FETCHED";
export const BLOCK_DATA_ERROR = "BLOCK_DATA_ERROR";

export const OPEN_LANGUAGE_MODAL = "OPEN_LANGUAGE_MODAL";
export const CLOSE_LANGUAGE_MODAL = "CLOSE_LANGUAGE_MODAL";
